dist: trusty
os:
  - linux  
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc

# Install dependencies
before_install:
  - sudo apt-get update
  # Install Boost
  - sudo apt-get install libboost-all-dev
  # Download and install OpenCV
  - wget https://github.com/opencv/opencv/archive/3.4.0.zip -O opencv.zip
  - unzip opencv.zip
  - wget https://github.com/opencv/opencv_contrib/archive/3.4.0.zip -O opencv_contrib.zip
  - unzip opencv_contrib.zip
  - mkdir opencv-3.4.0/build
  - cd opencv-3.4.0/build
  - cmake -DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib-3.4.0/modules/ \
      -DBUILD_opencv_python3=OFF \
      -DBUILD_TESTS=OFF \
      -DBUILD_PERF_TESTS=OFF \
      -DBUILD_opencv_java=OFF ..
  - sudo make -j4 install
  - rm /opencv.zip
  - rm /opencv_contrib.zip
  - rm -r /opencv-3.4.0
  - rm -r /opencv_contrib-3.4.0
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
